name: 'Bump Version'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose a version: <major|minor|patch>'
        required: true
        default: 'minor'

jobs:
  bump-version:
    name: 'Bump Version on main branch'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'

      - name: 'cat package.json'
        run: cat ./package.json

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v9.1.0
        id: version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          version-type: ${{ github.event.inputs.environment }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
